version: "3.8"

networks:
  app-tier:
    driver: bridge

services:
  db:
    image: mysql
    container_name: "database"
    restart: always
    expose:
      - "3306"
    ports:
      - "33006:3306"
    networks:
      - app-tier
    environment:
         MYSQL_DATABASE: admin
         MYSQL_USER: root
         MYSQL_PASSWORD: root
         MYSQL_ROOT_PASSWORD: "admin"
         MYSQL_ROOT_HOST: '%'
    volumes:
        - .dbdata:/var/lib/mysql
        - ./init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
